# Generated by Django 5.2.8 on 2025-11-13 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_verificationrequest_reviewed_by"),
    ]

    def _assign_admin_role(apps, schema_editor):
        User = apps.get_model("accounts", "User")
        email = getattr(settings, "VERIFICATION_ADMIN_EMAIL", "").lower()
        if not email:
            return
        try:
            user = User.objects.get(email__iexact=email)
        except User.DoesNotExist:
            return
        user.is_staff = True
        user.is_superuser = True
        user.save(update_fields=["is_staff", "is_superuser"])

    def _noop(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(_assign_admin_role, reverse_code=_noop),
    ]
