# Generated by Django 5.2.8 on 2025-11-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_wallettransaction_notification_wallet"),
        ("marketplace", "0003_order_currency_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="related_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="marketplace.contract",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.wallet",
            ),
        ),
    ]
