# Generated by Django 5.2.8 on 2025-11-14 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="span_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="status_code",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="trace_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("logout_all", "Logout all"),
                    ("refresh", "Token refresh"),
                    ("2fa_enabled", "2FA enabled"),
                    ("2fa_disabled", "2FA disabled"),
                    ("password_reset_request", "Password reset requested"),
                    ("password_reset_confirm", "Password reset confirmed"),
                    ("email_verify_request", "Email verification requested"),
                    ("email_verify_confirm", "Email verification confirmed"),
                    ("email_change_request", "Email change requested"),
                    ("email_change_confirm", "Email change confirmed"),
                    ("kyc_upload", "KYC document uploaded"),
                    ("kyc_view", "KYC document accessed"),
                    ("role_change", "Role changed"),
                    ("access_denied", "Access denied"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
