# Generated by Django 5.2.8 on 2025-11-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_assign_admin_fdilov1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
