# Generated by Django 5.2.8 on 2025-11-16 00:41

import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


def drop_legacy_profile_slug_index(apps, schema_editor):
    """Drop the legacy LIKE index that may linger on older databases."""

    if schema_editor.connection.vendor != "postgresql":  # pragma: no cover - safety
        return

    index_name = "accounts_profile_slug_8a7a322e_like"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT n.nspname
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind = 'i' AND c.relname = %s
            """,
            [index_name],
        )
        schemas = [row[0] for row in cursor.fetchall()]

        # Drop the index for every schema it may exist in. Afterwards, perform a
        # final drop without the schema qualifier as a best-effort fallback so
        # we cover databases that rely on the current search path.
        quote = schema_editor.quote_name
        for schema in schemas:
            cursor.execute(
                f"DROP INDEX IF EXISTS {quote(schema)}.{quote(index_name)} CASCADE"
            )

        cursor.execute(
            f"DROP INDEX IF EXISTS {quote(index_name)} CASCADE"
        )


def populate_profile_slugs(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")

    for profile in Profile.objects.filter(slug__isnull=True).iterator():
        profile.slug = str(uuid.uuid4())
        profile.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_delete_notification"),
        ("marketplace", "0005_skillsynonym_category_description_ru_and_more"),
    ]

    # The first operation explicitly drops an index. Running this migration in a
    # non-atomic mode ensures that, once the drop succeeds, PostgreSQL commits
    # it immediately and the subsequent schema changes never see the old index.
    atomic = False

    operations = [
        # In some environments a previous slug field or index may still exist
        # even though the migration history does not contain it. When Django
        # tries to add or alter the slug field it attempts to recreate the
        # accompanying index, which results in PostgreSQL raising a
        # ``DuplicateTable`` error because the index (named
        # ``accounts_profile_slug_8a7a322e_like``) is already present. To keep
        # the migration idempotent we explicitly drop that leftover index if it
        # exists before proceeding with the new field additions.
        migrations.RunPython(
            drop_legacy_profile_slug_index, migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("project", "Project-based"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_pref",
            field=models.CharField(
                choices=[
                    ("platform", "Platform"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                ],
                default="platform",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="min_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(
                blank=True, db_index=False, max_length=160, null=True
            ),
        ),
        migrations.RunPython(populate_profile_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(
                db_index=False, default=uuid.uuid4, max_length=160, unique=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("link_only", "Link-only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["languages"], name="profile_languages_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["hourly_rate", "min_budget"], name="profile_rate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_verified", "visibility"], name="profile_verified_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["last_activity_at"], name="profile_last_activity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["slug"],
                name="profile_slug_like_idx",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
    ]
