# Generated by Django 5.2.8 on 2025-11-16 00:41

import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


def populate_profile_slugs(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")

    for profile in Profile.objects.filter(slug__isnull=True).iterator():
        profile.slug = str(uuid.uuid4())
        profile.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_delete_notification"),
        ("marketplace", "0005_skillsynonym_category_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("project", "Project-based"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_pref",
            field=models.CharField(
                choices=[
                    ("platform", "Platform"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                ],
                default="platform",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="min_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, null=True),
        ),
        migrations.RunPython(populate_profile_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("link_only", "Link-only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["languages"], name="profile_languages_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["hourly_rate", "min_budget"], name="profile_rate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_verified", "visibility"], name="profile_verified_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["last_activity_at"], name="profile_last_activity_idx"
            ),
        ),
    ]
