# Generated by Django 5.2.8 on 2025-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_availability_profile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tldr_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tldr_uz",
            field=models.TextField(blank=True),
        ),
    ]
