# Generated by Django 5.2.8 on 2025-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_tldr_ru_profile_tldr_uz"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("normalized_email", models.EmailField(blank=True, max_length=254)),
                ("nickname", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("patronymic", models.CharField(blank=True, max_length=150)),
                ("birth_year", models.PositiveIntegerField(blank=True, null=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("locale", models.CharField(default="ru", max_length=8)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("otp_hash", models.CharField(max_length=128)),
                ("otp_salt", models.CharField(max_length=32)),
                ("otp_expires_at", models.DateTimeField()),
                ("attempts_left", models.PositiveSmallIntegerField(default=5)),
                ("resend_available_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.PositiveSmallIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="accounts_pe_email_d113e3_idx"),
                    models.Index(
                        fields=["normalized_email"],
                        name="accounts_pe_normali_0817af_idx",
                    ),
                ],
            },
        ),
    ]
