# Generated by Django 5.2.8 on 2025-11-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('registration_started', 'Registration started'), ('registration_code_sent', 'Registration code sent'), ('registration_verified', 'Registration verified'), ('login', 'Login'), ('logout', 'Logout'), ('logout_all', 'Logout all'), ('refresh', 'Token refresh'), ('2fa_enabled', '2FA enabled'), ('2fa_disabled', '2FA disabled'), ('password_reset_request', 'Password reset requested'), ('password_reset_confirm', 'Password reset confirmed'), ('email_verify_request', 'Email verification requested'), ('email_verify_confirm', 'Email verification confirmed'), ('email_change_request', 'Email change requested'), ('email_change_confirm', 'Email change confirmed'), ('kyc_upload', 'KYC document uploaded'), ('kyc_view', 'KYC document accessed'), ('role_change', 'Role changed'), ('access_denied', 'Access denied')], max_length=32),
        ),
    ]
