# Generated by Django 5.2.8 on 2025-11-15 21:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0010_delete_notification"),
        ("chat", "0002_alter_chatattachment_file"),
        ("disputes", "0001_initial"),
        ("marketplace", "0004_contract_escrow_frozen_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("contract", "Contract"),
                            ("payments", "Payments"),
                            ("account", "Account"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("chat.new_message", "Chat: new message"),
                            ("chat.mention", "Chat: mention"),
                            ("contract.created", "Contract created"),
                            ("contract.signed", "Contract signed"),
                            ("contract.delivered", "Deliverable uploaded"),
                            ("contract.dispute_opened", "Dispute opened"),
                            ("contract.dispute_closed", "Dispute closed"),
                            ("contract.application_submitted", "Application submitted"),
                            ("contract.application_decision", "Application decision"),
                            ("contract.termination_requested", "Termination requested"),
                            ("contract.termination_approved", "Termination approved"),
                            ("contract.completed", "Contract completed"),
                            ("payments.hold", "Funds on hold"),
                            ("payments.release", "Funds released"),
                            ("payments.payout", "Payout sent"),
                            ("account.login", "Account login"),
                            ("account.2fa", "Two-factor challenge"),
                            ("account.password_reset", "Password reset"),
                            ("account.generic", "Account event"),
                        ],
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("dedupe_key", models.CharField(blank=True, max_length=255)),
                ("throttle_until", models.DateTimeField(blank=True, null=True)),
                ("digest_key", models.CharField(blank=True, max_length=255)),
                ("digest_window", models.DurationField(blank=True, null=True)),
                ("is_digest", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_events",
                        to="accounts.profile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NotificationDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("contract", "Contract"),
                            ("payments", "Payments"),
                            ("account", "Account"),
                        ],
                        max_length=32,
                    ),
                ),
                ("channel", models.CharField(max_length=32)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="digests",
                        to="notifications.notificationevent",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_for", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-app"),
                            ("email", "Email"),
                            ("web_push", "Web push"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                            ("digested", "Digest queued"),
                            ("throttled", "Throttled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("quieted_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="notifications.notificationdigest",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("contract", "Contract"),
                            ("payments", "Payments"),
                            ("account", "Account"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-app"),
                            ("email", "Email"),
                            ("web_push", "Web push"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Сразу"),
                            ("digest_15m", "Каждые 15 минут"),
                            ("hourly", "Каждый час"),
                            ("daily", "Раз в день"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="ru", max_length=8)),
                ("timezone", models.CharField(default="Asia/Tashkent", max_length=64)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("time_window_start", models.TimeField(blank=True, null=True)),
                ("time_window_end", models.TimeField(blank=True, null=True)),
                (
                    "daily_digest_hour",
                    models.PositiveSmallIntegerField(
                        default=9,
                        help_text="24h format hour when daily digests may be sent.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user", "category"),
            },
        ),
        migrations.CreateModel(
            name="SlaActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_actions",
                        to="chat.chatthread",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_actions",
                        to="marketplace.contract",
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_actions",
                        to="disputes.disputecase",
                    ),
                ),
            ],
            options={
                "ordering": ("-triggered_at",),
            },
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["recipient", "is_read"], name="notificatio_recipie_aa585e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["dedupe_key", "recipient"],
                name="notificatio_dedupe__becf01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["digest_key", "recipient"],
                name="notificatio_digest__fa8dd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdigest",
            index=models.Index(
                fields=["channel", "status"], name="notificatio_channel_190fcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdigest",
            index=models.Index(
                fields=["scheduled_for"], name="notificatio_schedul_e4c03e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel", "status"], name="notificatio_channel_edd073_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "category", "channel")},
        ),
        migrations.AddIndex(
            model_name="slaactionlog",
            index=models.Index(
                fields=["rule_code", "triggered_at"],
                name="notificatio_rule_co_a23fba_idx",
            ),
        ),
    ]
