"""
Django settings for obsidian_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

from . import jwt_settings as jwt_conf

try:  # pragma: no cover - optional dependency handling
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except ModuleNotFoundError:  # The SDK is optional for local development
    sentry_sdk = None
    DjangoIntegration = None


def get_bool_env(var_name, default=False):
    """Parse boolean environment variables."""

    value = os.getenv(var_name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def get_list_env(var_name, default=None):
    """Parse comma-separated environment variables into a list."""

    value = os.getenv(var_name)
    if value is None or value.strip() == "":
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-)46r5j1goadmb5x#!_1p8*$z7k=9c)n(snh%#+i=+-uwm^%@uy",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env("DJANGO_DEBUG", default=True)

ENVIRONMENT = os.getenv("DJANGO_ENVIRONMENT", "dev").lower()

ALLOWED_HOSTS = get_list_env(
    "DJANGO_ALLOWED_HOSTS",
    default=[
        "localhost",
        "127.0.0.1",
        "::1",
    ],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    # Local apps
    "accounts",
    "marketplace",
    "uploads",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "obsidian_backend.middleware.SecurityHeadersMiddleware",
    "obsidian_backend.middleware.AdminAccessMiddleware",
]

ROOT_URLCONF = "obsidian_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "obsidian_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv(
            "DATABASE_URL",
            "postgresql://postgres:QodMCrMqhbvgtMsxuOlgKBgoZpOWcABE@trolley.proxy.rlwy.net:30558/railway",
        ),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "accounts.validators.PasswordComplexityValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "accounts.validators.CommonPasswordListValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "accounts.permissions.RoleBasedAccessPermission",
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "accounts.throttling.LoginIPThrottle",
        "accounts.throttling.LoginUserThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "login_ip": os.getenv("AUTH_LOGIN_THROTTLE_IP", "10/min"),
        "login_user": os.getenv("AUTH_LOGIN_THROTTLE_USER", "5/min"),
    },
}

if jwt_conf.FEATURE_FLAGS.get("auth.token_legacy", False):
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = (
        "accounts.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    )

AUTH_REQUIRE_2FA_FOR_STAFF = jwt_conf.FEATURE_FLAGS.get("auth.2fa", False)

CORS_ENV_ORIGINS = {
    "dev": [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    "stage": [
        "https://stage.app.obsidian.dev",
        "https://stage-admin.obsidian.dev",
    ],
    "prod": [
        "https://app.obsidian.io",
        "https://admin.obsidian.io",
    ],
}

CORS_ALLOWED_ORIGINS = get_list_env(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default=CORS_ENV_ORIGINS.get(ENVIRONMENT, []),
)

CORS_ALLOW_CREDENTIALS = get_bool_env("DJANGO_CORS_ALLOW_CREDENTIALS", default=True)

CSRF_TRUSTED_ORIGINS = [origin for origin in CORS_ALLOWED_ORIGINS if origin.startswith("https://")]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = int(os.getenv("DJANGO_SESSION_COOKIE_AGE", 60 * 60 * 8))

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_AGE = int(os.getenv("DJANGO_CSRF_COOKIE_AGE", 60 * 60 * 8))

SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", 60 * 60 * 24 * 365))
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
)
SECURE_HSTS_PRELOAD = get_bool_env("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv(
    "DJANGO_SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin"
)
X_FRAME_OPTIONS = "DENY"

CONTENT_SECURITY_POLICY = {
    "default-src": ["'self'"],
    "script-src": ["'self'", "https://cdn.obsidian.io"],
    "style-src": ["'self'", "https://fonts.googleapis.com"],
    "font-src": ["'self'", "https://fonts.gstatic.com"],
    "img-src": ["'self'", "data:", "https://cdn.obsidian.io"],
    "connect-src": ["'self'", *CORS_ALLOWED_ORIGINS],
    "frame-ancestors": ["'none'"],
}

ADMIN_BASE_PATH = os.getenv("DJANGO_ADMIN_PATH", "control-center/").strip("/") + "/"
ADMIN_ALLOWED_IPS = get_list_env("DJANGO_ADMIN_ALLOWED_IPS", default=[])
ADMIN_ALLOWED_ASN = get_list_env("DJANGO_ADMIN_ALLOWED_ASN", default=[])
ADMIN_REQUIRE_ROLES_2FA = {"staff", "moderator", "finance"}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

VERIFICATION_ADMIN_EMAIL = os.getenv("VERIFICATION_ADMIN_EMAIL", "")


SENTRY_DSN = os.getenv("SENTRY_DSN")
SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", "dev")
SENTRY_RELEASE = os.getenv("SENTRY_RELEASE") or "TODO_SET_RELEASE"


FEATURE_FLAGS = jwt_conf.FEATURE_FLAGS

JWT_SETTINGS = {
    "environment": jwt_conf.JWT_ENVIRONMENT,
    "access_ttl_seconds": jwt_conf.JWT_ACCESS_TTL_SECONDS,
    "refresh_ttl_seconds": jwt_conf.JWT_REFRESH_TTL_SECONDS,
    "refresh_sliding_window_seconds": jwt_conf.JWT_REFRESH_SLIDING_WINDOW_SECONDS,
    "refresh_absolute_lifetime_seconds": jwt_conf.JWT_REFRESH_ABSOLUTE_LIFETIME_SECONDS,
    "refresh_cookie": jwt_conf.JWT_REFRESH_COOKIE,
    "access_keys": jwt_conf.JWT_ACCESS_KEYS,
    "refresh_keys": jwt_conf.JWT_REFRESH_KEYS,
    "keyrings": jwt_conf.JWT_KEYRINGS,
}

if SENTRY_DSN and sentry_sdk and DjangoIntegration:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.2")),
        profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.2")),
        send_default_pii=True,
    )
