# Generated by Django 5.2.8 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_shadow_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
