# Generated by Django 5.2.8 on 2025-11-15 21:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dell\\Рабочий стол\\Obsidian_freelance\\backend\\private_media'), upload_to='chat/attachments/%Y/%m/%d'),
        ),
    ]
