# Generated by Django 5.2.8 on 2025-11-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatattachment_file'),
        ('chat', '0002_chatmessage_is_shadow_blocked'),
    ]

    operations = [
    ]
