# Generated by Django 5.2.8 on 2025-11-15 23:59

import uploads.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_merge_20251116_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(max_length=512, storage=uploads.storage.PrivateMediaStorage(), upload_to='chat/attachments/%Y/%m/%d'),
        ),
    ]
