# Generated by Django 5.2.8 on 2025-11-14 22:09

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("portfolio", "Portfolio"), ("kyc", "KYC")],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/workspace/Obsidian_freelance/backend/private_media"
                        ),
                        upload_to="secure",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=64)),
                ("checksum", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secure_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SecureDocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="uploads.securedocument",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="securedocument",
            index=models.Index(
                fields=["owner", "category"], name="uploads_sec_owner_i_498954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securedocumentlink",
            index=models.Index(
                fields=["document", "expires_at"], name="uploads_sec_documen_d5ee8a_idx"
            ),
        ),
    ]
