# Generated by Django 5.2.8 on 2025-11-14 22:40

from django.db import migrations, models

import uploads.storage


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedocument',
            name='file',
            field=models.FileField(
                max_length=512,
                storage=uploads.storage.private_storage,
                upload_to='secure',
            ),
        ),
    ]
