# Generated by Django 5.2.8 on 2025-11-14 22:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedocument',
            name='file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Dell\\Рабочий стол\\Obsidian_freelance\\backend\\private_media'), upload_to='secure'),
        ),
    ]
