# Generated by Django 5.2.8 on 2025-11-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_wallettransaction_notification_wallet"),
        ("marketplace", "0002_seed_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="UZS", max_length=10),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_signatures", "Ожидает подписания"),
                            ("active", "Активен"),
                            ("completed", "Завершён"),
                            ("termination_requested", "Запрошено расторжение"),
                            ("terminated", "Расторгнут"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending_signatures",
                        max_length=32,
                    ),
                ),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("freelancer_signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "termination_requested_by",
                    models.CharField(blank=True, max_length=20),
                ),
                ("termination_reason", models.TextField(blank=True)),
                (
                    "termination_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "termination_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("compensation_paid", models.BooleanField(default=False)),
                (
                    "budget_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="UZS", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="marketplace.orderapplication",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contracts",
                        to="accounts.profile",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_contracts",
                        to="accounts.profile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("order", "freelancer")},
            },
        ),
    ]
