# Generated by Django 5.2.8 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_order_currency_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="escrow_frozen_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contract",
            name="escrow_release_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
