# Generated by Django 5.2.8 on 2025-11-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_contract_escrow_frozen_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Russian"), ("uz", "Uzbek"), ("en", "English")],
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="marketplace.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="category",
            name="title_uz",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="description_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="popularity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_ru",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_uz",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="marketplace_category_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["slug"], name="marketplace_skill_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category", "name"], name="marketplace_skill_category_idx"
            ),
        ),
        migrations.AddField(
            model_name="skillsynonym",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="marketplace.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="skillsynonym",
            index=models.Index(
                fields=["language", "value"], name="skill_synonym_language_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillsynonym",
            unique_together={("skill", "language", "value")},
        ),
    ]
