# Generated by Django 5.2.8 on 2025-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_skillsynonym_category_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tldr_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tldr_uz",
            field=models.TextField(blank=True),
        ),
    ]
