# Generated by Django 5.2.8 on 2025-11-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0011_profile_availability_profile_bio_and_more"),
        ("marketplace", "0005_skillsynonym_category_description_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("problem", models.TextField()),
                ("solution", models.TextField()),
                ("result", models.TextField()),
                ("media", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("featured", models.BooleanField(default=False)),
                (
                    "client_permission",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("client_only", "Client only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("moderation", "Moderation"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("top_rated", "Top Rated"),
                            ("verified", "Verified"),
                            ("rising_talent", "Rising Talent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rules_snapshot", models.JSONField(blank=True, default=dict)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("invites", models.PositiveIntegerField(default=0)),
                (
                    "hire_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("response_time", models.DurationField(blank=True, null=True)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "dispute_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "escrow_share",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile stats",
                "verbose_name_plural": "Profile stats",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_scores", models.JSONField(blank=True, default=dict)),
                ("text", models.TextField()),
                ("helpful_votes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("blind_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.contract",
                    ),
                ),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to="accounts.profile",
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to="accounts.profile",
                    ),
                ),
                (
                    "target_portfolio_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="profiles.portfolioitem",
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to="accounts.profile",
                    ),
                ),
                (
                    "target_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="profiles.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="accounts.profile",
                    ),
                ),
                (
                    "favorite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client", "created_at"], name="favorite_created_idx"
                    )
                ],
                "unique_together": {("client", "favorite")},
            },
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(fields=["status"], name="portfolio_status_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolioitem",
            index=models.Index(
                fields=["profile", "featured"], name="portfolio_featured_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilebadge",
            index=models.Index(fields=["badge_type"], name="profile_badge_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="profilebadge",
            unique_together={("profile", "badge_type", "issued_at")},
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("contract", "rater"), name="unique_contract_rater"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_profile__isnull", False),
                    ("target_portfolio_item__isnull", False),
                    ("target_review__isnull", False),
                    _connector="OR",
                ),
                name="report_has_target",
            ),
        ),
    ]
